### ISSUE TITLE
Build errors using make (with OpenCV2)

### ISSUE THREAD

**Issue by Cypher1** [matteoserva/QwopBot#1]
A lot of OpenCV things are not declared (e.g. ORB).

Is this missing a #include or do I need an older version of OpenCV?

**Comment by matteoserva** [comment]
I compiled it with the debian opencv2 packages a while ago. I''ll check and get back to you soon

**Comment by matteoserva** [comment]
Just tested it on debian jessie. I had to install libopencv-dev and libxdo-dev.

**Comment by Cypher1** [comment]
Thanks. I'll try to get the arch equivalents and have another go

**Comment by matteoserva** [comment]
You can also create a debian chroot environment with debootstrap.
